[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="users" type="ru.itmo.tpl.model.User[]" --]
[#-- @ftlvariable name="user" type="ru.itmo.tpl.model.User" --]
[#-- @ftlvariable name="menuURI" type="ru.itmo.tpl.model.ComponentURI[]" --]
[#-- @ftlvariable name="posts" type="ru.itmo.tpl.model.Post[]" --]
